title: Patrick Michael Leitloff
logo: /assets/img/profile_pic2.png
description: Postgraduate Student at London School of Economics in Econometrics & Mathematical Economics
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
